# Generated by Django 4.0.4 on 2022-06-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gate', models.CharField(default='main', max_length=8)),
                ('regno', models.CharField(max_length=10)),
                ('ownercontact', models.CharField(max_length=15)),
                ('pdate', models.DateTimeField()),
                ('intime', models.CharField(max_length=50)),
                ('outtime', models.CharField(max_length=50)),
                ('parkingcharge', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.category')),
            ],
        ),
    ]
